let selectedFile, reportRows=[], reportReference='', worker, usingLocalProcessor=false;
const $=id=>document.getElementById(id);
const localProcessor=window.onmessage;
const nativePostMessage=window.postMessage.bind(window);
const classificationLabel=level=>level==='IMPEDITIVO'?'PRIORITÁRIO':level==='ATENÇÃO'?'SECUNDÁRIO':level;
const displayRuleText=value=>String(value).replaceAll('IMPEDITIVO','PRIORITÁRIO').replaceAll('ATENÇÃO','SECUNDÁRIO');
const REGRAS_APLICADAS=[
['1','Estrutura','O arquivo CSV ou TXT, separado por ponto e vírgula, deve conter todos os 23 cabeçalhos oficiais do FGTS.','IMPEDITIVO'],
['2','01 — Data de Referência','Deve estar preenchida no formato DD/MM/AAAA e representar uma data existente no calendário.','IMPEDITIVO'],
['3','01 — Data de Referência','Deve ser idêntica em todas as linhas do arquivo.','IMPEDITIVO'],
['4','02 — Data de Geração','Deve estar preenchida no formato DD/MM/AAAA e representar uma data existente no calendário.','IMPEDITIVO'],
['5','02 × 01 — Datas de Geração e Referência','A Data de Geração não pode ser anterior à Data de Referência.','IMPEDITIVO'],
['6','03 — Código de Agrupamento SNH','Não pode estar vazio.','IMPEDITIVO'],
['7','03 — Código de Agrupamento SNH','Deve ser único: não pode se repetir em outra linha do arquivo.','IMPEDITIVO'],
['8','04 — Código IBGE','Deve conter exatamente 6 dígitos numéricos.','IMPEDITIVO'],
['9','04 — Código IBGE','Deve existir na base territorial oficial DTB 2024 do IBGE.','IMPEDITIVO'],
['10','04 × 05 — Código IBGE e Município','O Município deve corresponder ao nome oficial associado ao Código IBGE na DTB 2024.','IMPEDITIVO'],
['11','04 × 17 — Código IBGE e Sigla da UF','A Sigla da UF deve corresponder à UF associada ao Código IBGE na DTB 2024.','IMPEDITIVO'],
['12','06 — Programa federal','Deve ser um dos valores permitidos: CVA, Fora MCMV/CVA ou MCMV.','IMPEDITIVO'],
['13','07 — Modalidade','Deve ser exatamente Financiamento.','IMPEDITIVO'],
['14','08 — Programa FGTS','Deve pertencer à lista de programas FGTS permitidos.','IMPEDITIVO'],
['15','09 — Data da Contratação','Deve estar no formato AAAAMM.','IMPEDITIVO'],
['16','09 × 20 × 21 — Data, Ano e Mês da Contratação','Os 6 dígitos de Data da Contratação devem ser a concatenação do Ano (AAAA) e do Mês (MM) informados.','IMPEDITIVO'],
['17','09 × 01 — Data da Contratação e Data de Referência','A Data da Contratação não pode ser posterior ao mês da Data de Referência.','IMPEDITIVO'],
['18','10 — Valor da Compra','Deve ser numérico e maior ou igual a zero.','IMPEDITIVO'],
['19','11 — Valor do Financiamento','Deve ser numérico e maior ou igual a zero.','IMPEDITIVO'],
['20','12 — Subsídio FGTS','Deve ser numérico e maior ou igual a zero.','IMPEDITIVO'],
['21','13 — Subsídio OGU','Deve ser numérico e maior ou igual a zero.','IMPEDITIVO'],
['22','10 × 11 — Valor da Compra e Valor do Financiamento','O Valor da Compra deve ser maior ou igual ao Valor do Financiamento.','IMPEDITIVO'],
['23','14 — Quantidade de contratos','Deve ser um número inteiro maior que zero.','IMPEDITIVO'],
['24','15 — Faixa','Deve pertencer à lista de faixas permitidas.','IMPEDITIVO'],
['25','16 — Tipo do imóvel','Quando informado, deve ser Novo ou Usado.','IMPEDITIVO'],
['26','16 — Tipo do imóvel','Campo vazio é classificado como ATENÇÃO; deve ser preenchido quando a informação estiver disponível.','ATENÇÃO'],
['27','18 — UF','Deve corresponder a uma das 27 unidades federativas permitidas.','IMPEDITIVO'],
['28','17 × 18 — Sigla da UF e UF','A Sigla da UF deve corresponder ao estado informado.','IMPEDITIVO'],
['29','18 × 19 — UF e Região','A Região deve corresponder ao estado informado.','IMPEDITIVO'],
['30','18 × 22 — UF e Sigla da região','A sigla da região deve corresponder ao estado informado.','IMPEDITIVO'],
['31','20 — Ano da contratação','Deve ter 4 dígitos e estar entre 2009 e o ano da Data de Referência.','IMPEDITIVO'],
['32','21 — Mês da contratação','Deve ser numérico e estar entre 1 e 12.','IMPEDITIVO'],
['33','23 — Fonte de recurso','Deve ser um dos valores permitidos: FGTS, Fundo Social ou SBPE.','IMPEDITIVO'],
['34','15 × 23 — Faixa e Fonte de recurso','Quando a Faixa for Faixa 3 FS, a Fonte de recurso deve ser Fundo Social.','IMPEDITIVO'],
['35','06 × 15 — Programa federal e Faixa','Para faixas MCMV, exceto Faixa 3 FS, Fora MCMV e Fora MCMV/CVA, o Programa federal deve ser MCMV ou CVA.','IMPEDITIVO']
];
function csvEscape(value){const text=String(value??'');return /[";\n\r]/.test(text)?`"${text.replaceAll('"','""')}"`:text;}
function csvText(rows){return `\uFEFF${rows.map(row=>row.map(csvEscape).join(';')).join('\r\n')}`;}
function crc32(bytes){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let i=0;i<8;i++)crc=(crc>>>1)^((crc&1)?0xedb88320:0);}return(crc^0xffffffff)>>>0;}
function zipStore(entries){const encoder=new TextEncoder(),local=[],central=[];let offset=0;for(const [name,text] of entries){const filename=encoder.encode(name),data=encoder.encode(text),crc=crc32(data),header=new Uint8Array(30+filename.length),view=new DataView(header.buffer);view.setUint32(0,0x04034b50,true);view.setUint16(4,20,true);view.setUint32(14,crc,true);view.setUint32(18,data.length,true);view.setUint32(22,data.length,true);view.setUint16(26,filename.length,true);header.set(filename,30);local.push(header,data);const directory=new Uint8Array(46+filename.length),dirView=new DataView(directory.buffer);dirView.setUint32(0,0x02014b50,true);dirView.setUint16(4,20,true);dirView.setUint16(6,20,true);dirView.setUint32(16,crc,true);dirView.setUint32(20,data.length,true);dirView.setUint32(24,data.length,true);dirView.setUint16(28,filename.length,true);dirView.setUint32(42,offset,true);directory.set(filename,46);central.push(directory);offset+=header.length+data.length;}const centralSize=central.reduce((sum,item)=>sum+item.length,0),end=new Uint8Array(22),endView=new DataView(end.buffer);endView.setUint32(0,0x06054b50,true);endView.setUint16(8,entries.length,true);endView.setUint16(10,entries.length,true);endView.setUint32(12,centralSize,true);endView.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});}
function renderSummary(summary){const rows=Object.entries(summary).sort((a,b)=>b[1]-a[1]);$('resumo').innerHTML=rows.length?`<table><thead><tr><th>Regra</th><th>Ocorrências</th><th>Classificação</th></tr></thead><tbody>${rows.map(([key,count])=>{const [rule,level]=key.split('|');return `<tr><td>${rule}</td><td>${count}</td><td>${classificationLabel(level)}</td></tr>`;}).join('')}</tbody></table>`:'<p class="muted">O processamento não identificou nenhuma inconsistência nos dados, baseando-se nas regras consideradas.</p>';}
const FGTS_HEADERS=['mcmv_fgts_01_dt_referencia','mcmv_fgts_02_dt_geracao','mcmv_fgts_03_cod_agrupamento_snh','mcmv_fgts_04_cod_ibge','mcmv_fgts_05_nome_municipio','mcmv_fgts_06_txt_programa_fed','mcmv_fgts_07_txt_modalidade','mcmv_fgts_08_txt_programa_fgts','mcmv_fgts_09_txt_dt_contratacao','mcmv_fgts_10_val_compra','mcmv_fgts_11_val_financiamento','mcmv_fgts_12_val_subsidio_fgts','mcmv_fgts_13_val_subsidio_ogu','mcmv_fgts_14_qtd_contratos','mcmv_fgts_15_txt_faixa','mcmv_fgts_16_txt_tipo_imovel','mcmv_fgts_17_txt_sigla_uf','mcmv_fgts_18_txt_uf','mcmv_fgts_19_txt_regiao','mcmv_fgts_20_txt_ano_contratacao','mcmv_fgts_21_txt_mes_contratacao','mcmv_fgts_22_txt_sigla_regiao','mcmv_fgts_23_txt_fonte_recurso'];
function fgtsIncidentHeaders(rule){const map=[[/Data de Referência/,[1]],[/Data de Geração/,[2]],[/Agrupamento SNH/,[3]],[/Código IBGE/,[4]],[/Município/,[4,5]],[/Programa federal/,[6]],[/Modalidade/,[7]],[/Programa FGTS/,[8]],[/Data da Contratação/,[9,20,21]],[/Valor da Compra.*Financiamento/,[10,11]],[/Valor da Compra/,[10]],[/Valor do Financiamento/,[11]],[/Subsídio FGTS/,[12]],[/Subsídio OGU/,[13]],[/Quantidade de contratos/,[14]],[/Faixa/,[15]],[/Tipo do imóvel/,[16]],[/Sigla da UF/,[17]],[/UF /,[18]],[/Região/,[19,22]],[/Ano da contratação/,[20]],[/Mês da contratação/,[21]],[/Fonte de recurso/,[23]]];const item=map.find(([pattern])=>pattern.test(rule));return item?item[1].map(number=>FGTS_HEADERS[number-1]):['Cabeçalho a identificar'];}
function annotateFgtsRule(rule){const labels=[['Data de Referência',1],['Data de Geração',2],['Código de Agrupamento SNH',3],['Código IBGE',4],['Município',5],['Programa federal',6],['Modalidade',7],['Programa FGTS',8],['Data da Contratação',9],['Valor da Compra',10],['Valor do Financiamento',11],['Subsídio FGTS',12],['Subsídio OGU',13],['Quantidade de contratos',14],['Faixa',15],['Tipo do imóvel',16],['Sigla da UF',17],['UF',18],['Sigla da região',22],['Região',19],['Ano da contratação',20],['Mês da contratação',21],['Fonte de recurso',23]];let annotated=rule;labels.sort((a,b)=>b[0].length-a[0].length).forEach(([label,number])=>{const expression=new RegExp(`${label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}(?!\\s*\\()`,'gi');annotated=annotated.replace(expression,match=>`${match} (${FGTS_HEADERS[number-1]})`);});return annotated;}
function incidentItems(summary, level){return Object.entries(summary).filter(([key])=>key.endsWith(`|${level}`)).sort((a,b)=>b[1]-a[1]).map(([key,count])=>{const rule=key.split('|')[0];return `- ${annotateFgtsRule(rule)}: ${count.toLocaleString('pt-BR')} ocorrência${count===1?'':'s'}.`;});}
function referenceLabel(value){if(!value)return 'não identificada';const [year,month,day]=value.split('-');return year&&month&&day?`${day}/${month}/${year}`:value;}
function renderIncident(summary){const impeditivos=incidentItems(summary,'IMPEDITIVO'),atencoes=incidentItems(summary,'ATENÇÃO'),items=[...impeditivos,...atencoes],reference=referenceLabel(reportReference),dataName=`Dados FGTS Contratação - Data de Referência: ${reference}`;$('texto-incidente').value=`Assunto: Incidente de dados — ${dataName}\n\nPrezados(as),\n\n1. Informamos a identificação de possíveis incidentes de dados na base “${dataName}”, submetida à conferência.\n\n2. Durante as validações realizadas, foram observadas as discrepâncias abaixo.\n\n${items.length?items.join('\n'):'- Não foram identificadas discrepâncias.'}\n\n3. Diante do exposto, solicitamos, por gentileza, que sejam verificadas as inconsistências apontadas e informado se decorrem de alguma particularidade na geração da base ou se devem ser corrigidas.\n\n4. Caso seja constatada alguma inconsistência, solicitamos, por gentileza, o encaminhamento de versão corrigida da base de dados.\n\nAtenciosamente,`;$('incidente').classList.remove('hidden');$('status-copia').textContent='';}
async function copyIncident(){const field=$('texto-incidente');try{await navigator.clipboard.writeText(field.value);}catch(_){field.select();document.execCommand('copy');}$('status-copia').className='status ok';$('status-copia').textContent='Texto copiado. Você pode ajustá-lo antes ou depois de colar no e-mail.';}
function receiveMessage(message){if(message.type==='progress'){$('barra').style.width=`${message.percent}%`;$('status').textContent=`Carregando e analisando: ${message.percent}% · ${message.records.toLocaleString('pt-BR')} registros.`;}
if(message.type==='complete'){reportRows=message.rows;reportReference=message.reference||'';const noIssues=message.impeditivos===0&&message.aceitaveis===0;$('registros').textContent=message.records.toLocaleString('pt-BR');$('impeditivos').textContent=message.impeditivos.toLocaleString('pt-BR');$('aceitaveis').textContent=message.aceitaveis.toLocaleString('pt-BR');renderSummary(message.summary);if(noIssues)$('incidente').classList.add('hidden');else renderIncident(message.summary);$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');$('processar').disabled=false;$('barra').style.width='100%';$('status').className='status ok';$('status').textContent=noIssues?'Conferência concluída. Nenhuma inconsistência foi identificada; baixe o Excel para consultar as regras consideradas.':'Conferência concluída. O relatório contém somente as ocorrências identificadas.';restorePostMessage();}
if(message.type==='error'){$('processar').disabled=false;$('status').className='status error';$('status').textContent=message.message;restorePostMessage();}}
function restorePostMessage(){if(usingLocalProcessor){window.postMessage=nativePostMessage;usingLocalProcessor=false;}}
function startProcessing(file){try{if(!worker){worker=new Worker('worker.js');worker.onmessage=event=>receiveMessage(event.data);worker.onerror=()=>startLocalProcessing(file);}worker.postMessage({type:'process',file});}catch(error){startLocalProcessing(file);}}
function startLocalProcessing(file){if(usingLocalProcessor)return;usingLocalProcessor=true;window.postMessage=message=>receiveMessage(message);$('status').textContent='Carregando e analisando localmente… 0%';Promise.resolve(localProcessor({data:{type:'process',file}})).catch(error=>receiveMessage({type:'error',message:error.message||'Não foi possível processar o arquivo CSV ou TXT.'}));}

$('arquivo').addEventListener('change',event=>{selectedFile=event.target.files[0];reportReference='';$('arquivo-nome').textContent=selectedFile?`${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(1)} MB`:'Nenhum arquivo selecionado.';$('processar').disabled=!selectedFile;$('resultado').classList.add('hidden');$('incidente').classList.add('hidden');$('status').textContent='';$('barra').style.width='0';});
$('processar').addEventListener('click',()=>{if(!selectedFile)return;reportRows=[];$('processar').disabled=true;$('barra').style.width='0';$('status').className='status';$('status').textContent='Carregando o arquivo e iniciando a conferência… 0%';startProcessing(selectedFile);});
function summaryRows(){const totals=reportRows.reduce((acc,row)=>{const key=`${row[1]}|${row[2]}`;acc[key]=(acc[key]||0)+1;return acc;},{});return Object.entries(totals).map(([key,count])=>{const [rule,level]=key.split('|');return [rule,count,classificationLabel(level)];});}
function buildSheet(rows,classificationColumn){const ws=XLSX.utils.aoa_to_sheet(rows);const cols=Math.max(...rows.map(row=>row.length));for(let r=0;r<rows.length;r++)for(let c=0;c<cols;c++){const address=XLSX.utils.encode_cell({r,c});if(!ws[address])continue;const level=r>0&&classificationColumn!==undefined?rows[r][classificationColumn]:'';ws[address].s={font:{bold:r===0},fill:{fgColor:{rgb:r===0?'D9D9D9':level==='PRIORITÁRIO'?'F4CCCC':level==='SECUNDÁRIO'?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}};}ws['!cols']=Array.from({length:cols},(_,index)=>({wch:index===1?62:index===4?45:22}));ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:0,c:0},e:{r:rows.length-1,c:cols-1}})};return ws;}
function downloadZipFallback(detailHeader,summaryHeader,summary,rulesHeader){const details=reportRows.map(row=>[row[0],row[1],classificationLabel(row[2]),...row.slice(3)]),rules=REGRAS_APLICADAS.map(row=>[...row.slice(0,2),displayRuleText(row[2]),classificationLabel(row[3])]);const blob=zipStore([['log_resumo.csv',csvText([summaryHeader,...summary])],['log_detalhamento.csv',csvText([detailHeader,...details])],['regras_aplicadas.csv',csvText([rulesHeader,...rules])]]);const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download=`relatorio_fgts_${new Date().toISOString().slice(0,10)}.zip`;link.click();URL.revokeObjectURL(link.href);}
$('baixar').addEventListener('click',()=>{const detailHeader=['Código de Agrupamento SNH','Regra não atendida','Classificação','Valor encontrado','Justificativa','Município','UF','Data de contratação'];const summaryHeader=['Regra não atendida','Quantidade de ocorrências','Classificação'];const rulesHeader=['Número da regra','Colunas','Regra','Classificação'];const summary=summaryRows(),details=reportRows.map(row=>[row[0],row[1],classificationLabel(row[2]),...row.slice(3)]),rules=REGRAS_APLICADAS.map(row=>[...row.slice(0,2),displayRuleText(row[2]),classificationLabel(row[3])]);if(!window.XLSX){$('status').className='status error';$('status').textContent='Não foi possível carregar o componente de geração do Excel. Verifique a conexão com a internet e tente novamente.';return;}if(reportRows.length>1048575){downloadZipFallback(detailHeader,summaryHeader,summary,rulesHeader);$('status').className='status';$('status').textContent='O detalhamento excede o limite de linhas do Excel; foi gerado um pacote ZIP de CSVs.';return;}const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,buildSheet([summaryHeader,...summary],2),'LOG RESUMO');XLSX.utils.book_append_sheet(book,buildSheet([detailHeader,...details],2),'LOG DETALHAMENTO');XLSX.utils.book_append_sheet(book,buildSheet([rulesHeader,...rules],3),'REGRAS APLICADAS');XLSX.writeFile(book,`relatorio_fgts_${new Date().toISOString().slice(0,10)}.xlsx`,{cellStyles:true});});
$('copiar-incidente').addEventListener('click',copyIncident);
