let mainFile,compFile,reportRows=[],rules=[],worker;const $=id=>document.getElementById(id);
const parseCsv=text=>{let f='',r=[],out=[],q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){f+='"';i++}else q=!q}else if(c===';'&&!q){r.push(f);f=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;r.push(f);out.push(r);r=[];f=''}else f+=c}if(f||r.length){r.push(f);out.push(r)}return out};
async function read(file){if(/\.xlsx$/i.test(file.name)){if(!window.XLSX)throw Error('O componente de leitura Excel não foi carregado.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',raw:false});return XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{header:1,defval:''})}return parseCsv(await file.text())}
function labels(){const a=$('assunto').value,g=$('agente').value;const allowed=g==='bb'&&a==='empreendimentos'?'Excel ou TXT':'CSV ou TXT';$('formatos').textContent=`${g==='bb'?'Banco do Brasil':'CAIXA'} — ${a==='empreendimentos'?'Empreendimentos':'Entregas'}: ${allowed}`}
function change(){labels();$('arquivo').value='';$('complementar').value='';mainFile=compFile=null;$('arquivo-nome').textContent='Nenhum arquivo selecionado.';$('complementar-nome').textContent='Nenhum arquivo complementar selecionado.';$('processar').disabled=true;$('resultado').classList.add('hidden')}
function summary(summary){const x=Object.entries(summary).sort((a,b)=>b[1]-a[1]);$('resumo').innerHTML=x.length?`<table><thead><tr><th>Regra</th><th>Ocorrências</th><th>Classificação</th></tr></thead><tbody>${x.map(([k,n])=>{const [r,l]=k.split('|');return `<tr><td>${r}</td><td>${n}</td><td>${l}</td></tr>`}).join('')}</tbody></table>`:'<p class="muted">Nenhuma inconsistência foi identificada.</p>'}
function onMessage(m){if(m.type==='progress'){$('barra').style.width=`${m.percent}%`;$('status').textContent=m.message}if(m.type==='complete'){reportRows=m.rows;rules=m.rules;$('registros').textContent=m.records.toLocaleString('pt-BR');$('impeditivos').textContent=m.impeditivos.toLocaleString('pt-BR');$('atencoes').textContent=m.atencoes.toLocaleString('pt-BR');summary(m.summary);$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');$('processar').disabled=false;$('barra').style.width='100%';$('status').className='status ok';$('status').textContent='Conferência concluída.'}if(m.type==='error'){$('processar').disabled=false;$('status').className='status error';$('status').textContent=m.message}}
function makeSheet(data,level){const ws=XLSX.utils.aoa_to_sheet(data),cols=Math.max(...data.map(r=>r.length));for(let r=0;r<data.length;r++)for(let c=0;c<cols;c++){const a=XLSX.utils.encode_cell({r,c});if(ws[a])ws[a].s={font:{bold:r===0},fill:{fgColor:{rgb:r===0?'D9D9D9':r&&data[r][level]==='IMPEDITIVO'?'F4CCCC':r&&data[r][level]==='ATENÇÃO'?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}}}ws['!cols']=Array.from({length:cols},(_,i)=>({wch:i===1?64:24}));return ws}
function download(){const totals={};reportRows.forEach(r=>{const k=`${r[2]}|${r[3]}`;totals[k]=(totals[k]||0)+1});const s=Object.entries(totals).map(([k,n])=>{const [r,l]=k.split('|');return[r,n,l]});const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,makeSheet([['Regra não atendida','Quantidade de ocorrências','Classificação'],...s],2),'LOG RESUMO');XLSX.utils.book_append_sheet(book,makeSheet([['Linha','APF','Regra não atendida','Classificação','Valor encontrado','Valor esperado'],...reportRows],3),'LOG DETALHAMENTO');XLSX.utils.book_append_sheet(book,makeSheet([['Número','Colunas','Regra','Classificação'],...rules],3),'REGRAS APLICADAS');XLSX.writeFile(book,`relatorio_dados_prioritarios_${new Date().toISOString().slice(0,10)}.xlsx`,{cellStyles:true})}
$('assunto').onchange=change;$('agente').onchange=change;$('arquivo').onchange=e=>{mainFile=e.target.files[0];$('arquivo-nome').textContent=mainFile?`${mainFile.name} — ${(mainFile.size/1048576).toFixed(1)} MB`:'Nenhum arquivo selecionado.';$('processar').disabled=!mainFile};$('complementar').onchange=e=>{compFile=e.target.files[0];$('complementar-nome').textContent=compFile?`${compFile.name} — ${(compFile.size/1048576).toFixed(1)} MB`:'Nenhum arquivo complementar selecionado.'};$('processar').onclick=async()=>{try{$('processar').disabled=true;$('status').className='status';$('status').textContent='Lendo arquivos…';$('barra').style.width='8%';const primary=await read(mainFile),companion=compFile?await read(compFile):null;if(!worker){worker=new Worker('prioritarios-worker.js?v=1');worker.onmessage=e=>onMessage(e.data);worker.onerror=()=>onMessage({type:'error',message:'Não foi possível iniciar o processador.'})}worker.postMessage({type:'process',primary,companion,assunto:$('assunto').value,agente:$('agente').value})}catch(e){onMessage({type:'error',message:e.message||'Não foi possível ler o arquivo.'})}};$('baixar').onclick=download;labels();
const queryAgent=new URLSearchParams(location.search).get('agente');if(['caixa','bb'].includes(queryAgent)){$('agente').value=queryAgent;$('agente').parentElement.classList.add('hidden');labels();}
