let mainFile, compFile, reportRows = [], rules = [], worker, reportReference = '';
const $ = id => document.getElementById(id);
const crossRules = new Set(['Arquivos cruzados devem possuir a mesma Data de Movimento.','APF de Entregas não foi localizado em Empreendimentos.','APF com UH Entregues não possui registro no arquivo de Entregas.','Soma das entregas diverge de UH Entregues.','Soma das entregas não pode superar UH Contratadas.']);

const parseCsv = text => { let field='', row=[], output=[], quoted=false; for(let i=0;i<text.length;i++){const char=text[i];if(char==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++}else quoted=!quoted}else if(char===';'&&!quoted){row.push(field);field=''}else if((char==='\n'||char==='\r')&&!quoted){if(char==='\r'&&text[i+1]==='\n')i++;row.push(field);output.push(row);row=[];field=''}else field+=char}if(field||row.length){row.push(field);output.push(row)}return output };
async function read(file) { if(/\.xlsx$/i.test(file.name)){if(!window.XLSX)throw Error('O componente de leitura Excel não foi carregado.');const book=XLSX.read(await file.arrayBuffer(),{type:'array',raw:false});return XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,defval:''})}return parseCsv(await file.text()) }

function labels(){const subject=$('assunto').value,agent=$('agente').value,allowed=agent==='bb'&&subject==='empreendimentos'?'Excel ou TXT':'CSV ou TXT';$('formatos').textContent=`${agent==='bb'?'Banco do Brasil':'CAIXA'} — ${subject==='empreendimentos'?'Empreendimentos':'Entregas'}: ${allowed}`}
function change(){labels();$('arquivo').value='';$('complementar').value='';mainFile=compFile=null;$('arquivo-nome').textContent='Nenhum arquivo selecionado.';$('complementar-nome').textContent='Nenhum arquivo complementar selecionado.';$('processar').disabled=true;$('resultado').classList.add('hidden');$('incidente').classList.add('hidden')}

function countLevel(data,level){return Object.entries(data).reduce((total,[entry,count])=>total+(entry.endsWith(`|${level}`)?count:0),0)}
function renderSummary(data,target){const entries=Object.entries(data).sort((a,b)=>b[1]-a[1]);$(target).innerHTML=entries.length?`<table><thead><tr><th>Regra</th><th>Ocorrências</th><th>Classificação</th></tr></thead><tbody>${entries.map(([entry,count])=>{const [rule,level]=entry.split('|');return `<tr><td>${rule}</td><td>${count}</td><td>${level}</td></tr>`}).join('')}</tbody></table>`:'<p class="muted">Nenhuma inconsistência foi identificada.</p>'}
function summary(all){const primary={},cross={};Object.entries(all).forEach(([entry,count])=>{const rule=entry.split('|')[0];(crossRules.has(rule)?cross:primary)[entry]=count});$('impeditivos').textContent=countLevel(primary,'IMPEDITIVO').toLocaleString('pt-BR');$('atencoes').textContent=countLevel(primary,'ATENÇÃO').toLocaleString('pt-BR');$('cruzado-impeditivos').textContent=countLevel(cross,'IMPEDITIVO').toLocaleString('pt-BR');$('cruzado-atencoes').textContent=countLevel(cross,'ATENÇÃO').toLocaleString('pt-BR');renderSummary(primary,'resumo-principal');renderSummary(cross,'resumo-cruzado');$('resultado-cruzado').classList.toggle('hidden',!Object.keys(cross).length)}

function makeSheet(data,level){const ws=XLSX.utils.aoa_to_sheet(data),columns=Math.max(...data.map(row=>row.length));for(let row=0;row<data.length;row++)for(let column=0;column<columns;column++){const address=XLSX.utils.encode_cell({r:row,c:column});if(ws[address])ws[address].s={font:{bold:row===0},fill:{fgColor:{rgb:row===0?'D9D9D9':row&&data[row][level]==='IMPEDITIVO'?'F4CCCC':row&&data[row][level]==='ATENÇÃO'?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}}}ws['!cols']=Array.from({length:columns},(_,index)=>({wch:index===1?64:24}));return ws}
function download(){const totals={};reportRows.forEach(row=>{const key=`${row[2]}|${row[3]}`;totals[key]=(totals[key]||0)+1});const rows=Object.entries(totals).map(([key,count])=>{const [rule,level]=key.split('|');return [rule,count,level]});const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,makeSheet([['Regra não atendida','Quantidade de ocorrências','Classificação'],...rows],2),'LOG RESUMO');XLSX.utils.book_append_sheet(book,makeSheet([['Linha','APF','Regra não atendida','Classificação','Valor encontrado','Valor esperado'],...reportRows],3),'LOG DETALHAMENTO');XLSX.utils.book_append_sheet(book,makeSheet([['Número','Colunas','Regra','Classificação'],...rules],3),'REGRAS APLICADAS');XLSX.writeFile(book,`relatorio_dados_prioritarios_${new Date().toISOString().slice(0,10)}.xlsx`,{cellStyles:true})}

function referenceLabel(value){const match=String(value||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return match?`${match[3]}/${match[2]}/${match[1]}`:(value||'não identificada')}
function emailItems(all,level){return Object.entries(all).filter(([entry])=>entry.endsWith(`|${level}`)).sort((a,b)=>b[1]-a[1]).map(([entry,count])=>`- ${entry.split('|')[0]}: ${count.toLocaleString('pt-BR')} ocorrência${count===1?'':'s'}.`)}
function renderIncident(all){const dataName=`Dados Prioritários ${$('assunto').value==='entregas'?'Entregas':'Empreendimentos'} — ${$('agente').value==='bb'?'Banco do Brasil':'CAIXA'} — Data de Referência: ${referenceLabel(reportReference)}`,items=[...emailItems(all,'IMPEDITIVO'),...emailItems(all,'ATENÇÃO')];$('texto-incidente').value=`Assunto: Incidente de dados — ${dataName}\n\nPrezados(as),\n\n1. Informamos a identificação de possíveis incidentes de dados na base “${dataName}”, submetida à conferência.\n\n2. Durante as validações realizadas, foram observadas as discrepâncias abaixo.\n\n${items.length?items.join('\n'):'- Não foram identificadas discrepâncias.'}\n\n3. Segue anexo o arquivo com as ocorrências identificadas, para apoio à análise e à verificação das inconsistências apontadas.\n\n4. Solicitamos, por gentileza, a informação sobre eventual particularidade na geração da base ou necessidade de correção. Caso seja constatada inconsistência, solicitamos o encaminhamento de versão corrigida da base de dados.\n\nAtenciosamente,`;$('incidente').classList.remove('hidden');$('status-copia').textContent=''}

function onMessage(message){if(message.type==='progress'){$('barra').style.width=`${message.percent}%`;$('status').textContent=message.message}if(message.type==='complete'){reportRows=message.rows;rules=message.rules;reportReference=message.reference||'';$('registros').textContent=message.records.toLocaleString('pt-BR');summary(message.summary);renderIncident(message.summary);$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');$('processar').disabled=false;$('barra').style.width='100%';$('status').className='status ok';$('status').textContent='Conferência concluída.'}if(message.type==='error'){$('processar').disabled=false;$('status').className='status error';$('status').textContent=message.message}}

$('assunto').onchange=change;$('agente').onchange=change;
$('arquivo').onchange=event=>{mainFile=event.target.files[0];$('arquivo-nome').textContent=mainFile?`${mainFile.name} — ${(mainFile.size/1048576).toFixed(1)} MB`:'Nenhum arquivo selecionado.';$('processar').disabled=!mainFile;$('incidente').classList.add('hidden')};
$('complementar').onchange=event=>{compFile=event.target.files[0];$('complementar-nome').textContent=compFile?`${compFile.name} — ${(compFile.size/1048576).toFixed(1)} MB`:'Nenhum arquivo complementar selecionado.'};
$('processar').onclick=async()=>{try{$('processar').disabled=true;$('status').className='status';$('status').textContent='Lendo arquivos…';$('barra').style.width='8%';const primary=await read(mainFile),companion=compFile?await read(compFile):null;if(!worker){worker=new Worker('prioritarios-worker-proxy.js?v=1');worker.onmessage=event=>onMessage(event.data);worker.onerror=()=>onMessage({type:'error',message:'Não foi possível iniciar o processador.'})}worker.postMessage({type:'process',primary,companion,assunto:$('assunto').value,agente:$('agente').value})}catch(error){onMessage({type:'error',message:error.message||'Não foi possível ler o arquivo.'})}};
$('baixar').onclick=download;$('copiar-incidente').onclick=async()=>{try{await navigator.clipboard.writeText($('texto-incidente').value)}catch(_){$('texto-incidente').select();document.execCommand('copy')}$('status-copia').className='status ok';$('status-copia').textContent='Texto copiado. Você pode ajustá-lo antes ou depois de colar no e-mail.'};
const queryAgent=new URLSearchParams(location.search).get('agente');if(['caixa','bb'].includes(queryAgent)){$('agente').value=queryAgent;$('agente').parentElement.classList.add('hidden');labels()}else labels();
