if(typeof importScripts==='function')importScripts('ibge-municipios.js');
const HEADERS=['rcb_01_dt_referencia','rcb_02_dt_geracao','rcb_04_cod_ibge','rcb_05_região','rcb_06_uf_imovel','rcb_07_sg_uf_imovel','rcb_08_no_municipio_imovel','rcb_09_sg_sexo','rcb_10_vr_renda_familiar_comprovada','rcb_11_pc_renda_informal','rcb_12_vr_avaliacao_terreno','rcb_13_faixa_renda','rcb_14_pc_taxa_juros_nominal_inicial','rcb_15_vr_financiamento','rcb_16_vr_recurso_proprio','rcb_18_vr_investimento','rcb_19_dt_assinatura','rcb_20_pz_financiamento'];
const STATES={ACRE:['AC','N','Norte'],ALAGOAS:['AL','NE','Nordeste'],AMAPA:['AP','N','Norte'],AMAZONAS:['AM','N','Norte'],BAHIA:['BA','NE','Nordeste'],CEARA:['CE','NE','Nordeste'],'DISTRITO FEDERAL':['DF','CO','Centro-Oeste'],'ESPIRITO SANTO':['ES','SE','Sudeste'],GOIAS:['GO','CO','Centro-Oeste'],MARANHAO:['MA','NE','Nordeste'],'MATO GROSSO':['MT','CO','Centro-Oeste'],'MATO GROSSO DO SUL':['MS','CO','Centro-Oeste'],'MINAS GERAIS':['MG','SE','Sudeste'],PARA:['PA','N','Norte'],PARAIBA:['PB','NE','Nordeste'],PARANA:['PR','S','Sul'],PERNAMBUCO:['PE','NE','Nordeste'],PIAUI:['PI','NE','Nordeste'],'RIO DE JANEIRO':['RJ','SE','Sudeste'],'RIO GRANDE DO NORTE':['RN','NE','Nordeste'],'RIO GRANDE DO SUL':['RS','S','Sul'],RONDONIA:['RO','N','Norte'],RORAIMA:['RR','N','Norte'],'SANTA CATARINA':['SC','S','Sul'],'SAO PAULO':['SP','SE','Sudeste'],SERGIPE:['SE','NE','Nordeste'],TOCANTINS:['TO','N','Norte']};
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase();
const municipality=v=>norm(v).replace(/[^A-Z0-9]+/g,' ').trim();
function number(value){const text=clean(value).replace(/\s/g,'');if(!text)return null;const comma=text.lastIndexOf(','),dot=text.lastIndexOf('.');let n=text;if(comma>=0&&dot>=0)n=comma>dot?text.replace(/\./g,'').replace(',','.'):text.replace(/,/g,'');else if(comma>=0)n=text.replace(',','.');else if(/^-?\d{1,3}(?:\.\d{3})+$/.test(text))n=text.replace(/\./g,'');const result=Number(n);return Number.isFinite(result)?result:NaN;}
function date(value){const m=clean(value).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return null;const d=new Date(+m[3],+m[2]-1,+m[1]);return d.getFullYear()===+m[3]&&d.getMonth()===+m[2]-1&&d.getDate()===+m[1]?d:null;}
function parser(onRow){let field='',row=[],quoted=false;return{push(chunk){for(let i=0;i<chunk.length;i++){const c=chunk[i];if(c==='"'){if(quoted&&chunk[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===';'&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&chunk[i+1]==='\n')i++;row.push(field);onRow(row);row=[];field='';}else field+=c;}},end(){if(field.length||row.length){row.push(field);onRow(row);}}};}
self.onmessage=async event=>{if(event.data.type!=='process')return;try{const file=event.data.file,rows=[],summary={};let headerMap,records=0,impeditivos=0,atencoes=0,firstReference='',currentLine=0;
const add=(cells,rule,level,actual,expected)=>{const get=h=>cells[headerMap[h]]??'';rows.push([currentLine,rule,level,actual??'',expected??'',clean(get(HEADERS[6])),clean(get(HEADERS[5])),clean(get(HEADERS[0]))]);summary[`${rule}|${level}`]=(summary[`${rule}|${level}`]||0)+1;if(level==='IMPEDITIVO')impeditivos++;else atencoes++;};
const check=(cells,line)=>{records++;currentLine=line;const get=h=>cells[headerMap[h]]??'';const ref=date(get(HEADERS[0])),generation=date(get(HEADERS[1])),ibge=clean(get(HEADERS[2])).replace(/\D/g,'');
if(!ref)add(cells,'Data de Referência deve estar no formato DD/MM/AAAA e representar data válida.','IMPEDITIVO',get(HEADERS[0]),'DD/MM/AAAA.');else if(!firstReference)firstReference=clean(get(HEADERS[0]));
if(!generation)add(cells,'Data de Geração deve estar no formato DD/MM/AAAA e representar data válida.','IMPEDITIVO',get(HEADERS[1]),'DD/MM/AAAA.');else if(ref&&generation>new Date())add(cells,'Data de Geração não pode estar no futuro.','ATENÇÃO',get(HEADERS[1]),'Data até hoje.');
if(!/^\d{6}$/.test(ibge))add(cells,'Código IBGE deve possuir 6 dígitos numéricos.','IMPEDITIVO',get(HEADERS[2]),'Código IBGE municipal de 6 dígitos.');else{const official=typeof IBGE_MUNICIPIOS!=='undefined'?IBGE_MUNICIPIOS[ibge]:null;if(!official)add(cells,'Código IBGE não foi localizado na base territorial DTB 2024.','IMPEDITIVO',ibge,'Código municipal existente na DTB 2024.');else{if(municipality(get(HEADERS[6]))!==municipality(official[0]))add(cells,'Município não corresponde ao Código IBGE.','IMPEDITIVO',get(HEADERS[6]),official[0]);if(norm(get(HEADERS[5]))!==official[1])add(cells,'Sigla da UF não corresponde ao Código IBGE.','IMPEDITIVO',get(HEADERS[5]),official[1]);}}
const state=STATES[norm(get(HEADERS[4]))];if(!state)add(cells,'UF do imóvel fora da lista de estados permitidos.','IMPEDITIVO',get(HEADERS[4]),'Nome de uma UF brasileira.');else{if(norm(get(HEADERS[5]))!==state[0])add(cells,'Sigla da UF não corresponde à UF do imóvel.','IMPEDITIVO',get(HEADERS[5]),state[0]);if(norm(get(HEADERS[3]))!==norm(state[2]))add(cells,'Região não corresponde à UF do imóvel.','IMPEDITIVO',get(HEADERS[3]),state[2]);}
if(!['M','F'].includes(norm(get(HEADERS[7]))))add(cells,'Sigla do Sexo deve ser M ou F.','IMPEDITIVO',get(HEADERS[7]),'M ou F.');
const monetary=[[HEADERS[8],'Valor da Renda Familiar Comprovada'],[HEADERS[10],'Valor de Avaliação do Terreno'],[HEADERS[13],'Valor do Financiamento'],[HEADERS[14],'Valor de Recursos Próprios'],[HEADERS[15],'Valor do Investimento']];const values={};monetary.forEach(([h,label])=>{const v=values[h]=number(get(h));if(!Number.isFinite(v)||v<0)add(cells,`${label} deve ser numérico e não negativo.`,'IMPEDITIVO',get(h),'Valor numérico maior ou igual a zero.');});
const informal=number(get(HEADERS[9])),interest=number(get(HEADERS[12]));if(!Number.isFinite(informal)||informal<0||informal>1000)add(cells,'Percentual de Renda Informal deve estar entre 0 e 1000.','IMPEDITIVO',get(HEADERS[9]),'Valor de 0 a 1000.');if(!Number.isFinite(interest)||interest<0||interest>100)add(cells,'Taxa de Juros Nominal Inicial deve estar entre 0 e 100.','IMPEDITIVO',get(HEADERS[12]),'Percentual de 0 a 100.');
const range=number(get(HEADERS[11])),eventDate=date(get(HEADERS[16])),rangeCutoff=new Date(2026,4,12);if(!Number.isInteger(range)||![1,2].includes(range))add(cells,'Faixa de Renda deve ser 1 ou 2.','IMPEDITIVO',get(HEADERS[11]),'1 ou 2.');else if(eventDate&&eventDate>=rangeCutoff&&range!==1)add(cells,'Faixa de Renda deve ser 1 para evento a partir de 12/05/2026.','ATENÇÃO',get(HEADERS[11]),'Faixa 1.');else if((!eventDate||eventDate<rangeCutoff)&&Number.isFinite(values[HEADERS[8]])&&((range===1&&values[HEADERS[8]]>3200)||(range===2&&values[HEADERS[8]]<=3200)))add(cells,'Faixa de Renda não corresponde à Renda Familiar Comprovada.','ATENÇÃO',get(HEADERS[11]),values[HEADERS[8]]<=3200?'Faixa 1.':'Faixa 2.');
const financing=values[HEADERS[13]],own=values[HEADERS[14]],investment=values[HEADERS[15]];if(Number.isFinite(financing)&&Number.isFinite(investment)&&Math.abs(financing-investment)>0.01)add(cells,'Valor do Financiamento deve ser igual ao Valor do Investimento.','ATENÇÃO',get(HEADERS[13]),get(HEADERS[15]));if(Number.isFinite(own)&&Number.isFinite(financing)&&own>=financing)add(cells,'Valor de Recursos Próprios deve ser menor que o Valor do Financiamento.','ATENÇÃO',get(HEADERS[14]),`Menor que ${get(HEADERS[13])}.`);[[HEADERS[8],'Valor da Renda Familiar Comprovada'],[HEADERS[13],'Valor do Financiamento'],[HEADERS[15],'Valor do Investimento']].forEach(([h,label])=>{if(values[h]===0)add(cells,`${label} está zerado.`,'ATENÇÃO',get(h),'Valor a revisar.');});
const signature=date(get(HEADERS[16]));if(!signature)add(cells,'Data da Assinatura deve estar no formato DD/MM/AAAA e representar data válida.','IMPEDITIVO',get(HEADERS[16]),'DD/MM/AAAA.');else if(ref&&signature>ref)add(cells,'Data da Assinatura não pode ser posterior à Data de Referência.','IMPEDITIVO',get(HEADERS[16]),`Até ${String(ref.getDate()).padStart(2,'0')}/${String(ref.getMonth()+1).padStart(2,'0')}/${ref.getFullYear()}.`);else if(generation&&signature>generation)add(cells,'Data da Assinatura não pode ser posterior à Data de Geração.','IMPEDITIVO',get(HEADERS[16]),get(HEADERS[1]));
const term=number(get(HEADERS[17]));if(!Number.isInteger(term)||term<=0)add(cells,'Prazo do Financiamento deve ser inteiro maior que zero.','IMPEDITIVO',get(HEADERS[17]),'Número inteiro maior que zero.');};
let headerRead=false,lineNumber=0;const p=parser(cells=>{lineNumber++;if(!headerRead){const headers=cells.map((v,i)=>i===0?clean(v).replace(/^\uFEFF/,''):clean(v)),normalizedHeaders=headers.map(norm);const missing=HEADERS.filter(h=>!normalizedHeaders.includes(norm(h)));if(missing.length)throw new Error(`Cabeçalhos obrigatórios ausentes: ${missing.join(', ')}`);headerMap=Object.fromEntries(HEADERS.map(h=>[h,normalizedHeaders.indexOf(norm(h))]));headerRead=true;return;}if(cells.some(v=>clean(v)!==''))check(cells,lineNumber);});
const reader=file.stream().getReader(),decoder=new TextDecoder('utf-8');let read=0,last=0;while(true){const {value,done}=await reader.read();if(done)break;read+=value.byteLength;p.push(decoder.decode(value,{stream:true}));if(Date.now()-last>150){last=Date.now();self.postMessage({type:'progress',records,percent:Math.min(99,Math.round(read/file.size*100))});}}p.push(decoder.decode());p.end();if(!headerRead)throw new Error('Arquivo CSV ou TXT vazio.');self.postMessage({type:'complete',records,impeditivos,atencoes,summary,rows,reference:firstReference});}catch(error){self.postMessage({type:'error',message:error.message||'Não foi possível processar o arquivo.'});}};
