let selectedFile,reportRows=[],reportReference='',worker;
const $=id=>document.getElementById(id);
const classificationLabel=level=>level==='IMPEDITIVO'?'PRIORITÁRIO':level==='ATENÇÃO'?'SECUNDÁRIO':level;
const displayRuleText=value=>String(value).replaceAll('IMPEDITIVO','PRIORITÁRIO').replaceAll('ATENÇÃO','SECUNDÁRIO');
const REGRAS=[['1','Estrutura','O arquivo CSV ou TXT, separado por ponto e vírgula, deve conter os 18 cabeçalhos oficiais do Reforma Casa Brasil.','IMPEDITIVO'],['2','Data de referência','Deve estar preenchida no formato DD/MM/AAAA e representar data válida.','IMPEDITIVO'],['3','Data de geração','Deve estar preenchida no formato DD/MM/AAAA e representar data válida.','IMPEDITIVO'],['4','Código IBGE, município, UF, sigla e região','Os dados territoriais devem existir e corresponder entre si segundo a DTB 2024 do IBGE.','IMPEDITIVO'],['5','Sigla do sexo','Deve ser M ou F.','IMPEDITIVO'],['6','Valores monetários','Renda, terreno, financiamento, recursos próprios e investimento devem ser numéricos e não negativos.','IMPEDITIVO'],['7','Percentual de renda informal','Deve estar entre 0 e 1000.','IMPEDITIVO'],['8','Taxa de juros nominal inicial','Deve estar entre 0 e 100.','IMPEDITIVO'],['9','Faixa de renda e renda familiar','Até 11/05/2026, Faixa 1 corresponde à renda até R$ 3.200,00 e Faixa 2 à renda acima desse valor. A partir de 12/05/2026, a Faixa de Renda deve ser 1, independentemente da renda.','ATENÇÃO'],['10','Financiamento e investimento','O Valor do Financiamento deve ser igual ao Valor do Investimento.','ATENÇÃO'],['11','Recursos próprios e financiamento','Recursos Próprios deve ser menor que o Valor do Financiamento.','ATENÇÃO'],['12','Datas de assinatura e referência','A Data da Assinatura não pode ser posterior à Data de Referência nem à Data de Geração.','IMPEDITIVO'],['13','Prazo do financiamento','Deve ser inteiro maior que zero.','IMPEDITIVO'],['14','Renda, financiamento e investimento','Valores zerados devem ser revisados.','ATENÇÃO']];
function renderSummary(summary){const rows=Object.entries(summary).sort((a,b)=>b[1]-a[1]);$('resumo').innerHTML=rows.length?`<table><thead><tr><th>Regra</th><th>Ocorrências</th><th>Classificação</th></tr></thead><tbody>${rows.map(([k,n])=>{const [r,l]=k.split('|');return `<tr><td>${r}</td><td>${n}</td><td>${classificationLabel(l)}</td></tr>`}).join('')}</tbody></table>`:'<p class="muted">O processamento não identificou nenhuma inconsistência nos dados, baseando-se nas regras consideradas.</p>';}
function referenceLabel(v){return /^\d{6}$/.test(v)?`${v.slice(4)}/${v.slice(0,4)}`:(v||'não identificada');}
function incident(summary){const items=['IMPEDITIVO','ATENÇÃO'].flatMap(level=>Object.entries(summary).filter(([k])=>k.endsWith(`|${level}`)).sort((a,b)=>b[1]-a[1]).map(([k,n])=>`- ${k.split('|')[0]}: ${n.toLocaleString('pt-BR')} ocorrência${n===1?'':'s'}.`));const name=`Dados Reforma Casa Brasil Contratação - Data de Referência: ${referenceLabel(reportReference)}`;$('texto-incidente').value=`Assunto: Incidente de dados — ${name}\n\nPrezados(as),\n\n1. Informamos a identificação de possíveis incidentes de dados na base “${name}”, submetida à conferência.\n\n2. Durante as validações realizadas, foram observadas as discrepâncias abaixo.\n\n${items.length?items.join('\n'):'- Não foram identificadas discrepâncias.'}\n\n3. Solicitamos, por gentileza, a verificação das inconsistências apontadas e a informação sobre eventual particularidade na geração da base ou necessidade de correção.\n\n4. Caso seja constatada inconsistência, solicitamos o encaminhamento de versão corrigida da base de dados.\n\nAtenciosamente,`;$('incidente').classList.remove('hidden');}
function receive(m){if(m.type==='progress'){$('barra').style.width=`${m.percent}%`;$('status').textContent=`Carregando e analisando: ${m.percent}% · ${m.records.toLocaleString('pt-BR')} registros.`;}if(m.type==='complete'){reportRows=m.rows;reportReference=m.reference||'';const noIssues=m.impeditivos===0&&m.atencoes===0;$('registros').textContent=m.records.toLocaleString('pt-BR');$('impeditivos').textContent=m.impeditivos.toLocaleString('pt-BR');$('atencoes').textContent=m.atencoes.toLocaleString('pt-BR');renderSummary(m.summary);if(noIssues)$('incidente').classList.add('hidden');else incident(m.summary);$('resultado').classList.remove('hidden');$('baixar').classList.remove('hidden');$('processar').disabled=false;$('barra').style.width='100%';$('status').className='status ok';$('status').textContent=noIssues?'Conferência concluída. Nenhuma inconsistência foi identificada; baixe o Excel para consultar as regras consideradas.':'Conferência concluída. O relatório contém somente as ocorrências identificadas.';}if(m.type==='error'){$('processar').disabled=false;$('status').className='status error';$('status').textContent=m.message;}}
function process(file){try{if(!worker){worker=new Worker('rcb-worker.js?v=6');worker.onmessage=e=>receive(e.data);worker.onerror=()=>receive({type:'error',message:'Não foi possível iniciar o processador do arquivo.'});}worker.postMessage({type:'process',file});}catch(_){receive({type:'error',message:'Não foi possível iniciar o processador do arquivo.'});}}
$('arquivo').addEventListener('change',e=>{selectedFile=e.target.files[0];$('arquivo-nome').textContent=selectedFile?`${selectedFile.name} — ${(selectedFile.size/1024/1024).toFixed(1)} MB`:'Nenhum arquivo selecionado.';$('processar').disabled=!selectedFile;$('resultado').classList.add('hidden');$('incidente').classList.add('hidden');$('status').textContent='';$('barra').style.width='0';});
$('processar').addEventListener('click',()=>{if(!selectedFile)return;reportRows=[];$('processar').disabled=true;$('status').className='status';$('status').textContent='Carregando o arquivo e iniciando a conferência… 0%';process(selectedFile);});
function summaryRows(){const all={};reportRows.forEach(r=>{const k=`${r[1]}|${r[2]}`;all[k]=(all[k]||0)+1;});return Object.entries(all).map(([k,n])=>{const [r,l]=k.split('|');return[r,n,classificationLabel(l)];});}
function sheet(rows,classCol){const ws=XLSX.utils.aoa_to_sheet(rows),cols=Math.max(...rows.map(r=>r.length));for(let r=0;r<rows.length;r++)for(let c=0;c<cols;c++){const a=XLSX.utils.encode_cell({r,c});if(!ws[a])continue;const level=r&&classCol!==undefined?rows[r][classCol]:'';ws[a].s={font:{bold:r===0},fill:{fgColor:{rgb:r===0?'D9D9D9':level==='PRIORITÁRIO'?'F4CCCC':level==='SECUNDÁRIO'?'FFF2CC':'FFFFFF'}},border:{top:{style:'thin',color:{rgb:'000000'}},bottom:{style:'thin',color:{rgb:'000000'}},left:{style:'thin',color:{rgb:'000000'}},right:{style:'thin',color:{rgb:'000000'}}}};}ws['!cols']=Array.from({length:cols},(_,i)=>({wch:i===1?62:i===4?42:24}));ws['!autofilter']={ref:XLSX.utils.encode_range({s:{r:0,c:0},e:{r:rows.length-1,c:cols-1}})};return ws;}
$('baixar').addEventListener('click',()=>{if(!window.XLSX){$('status').className='status error';$('status').textContent='Não foi possível carregar o componente de geração do Excel.';return;}if(reportRows.length>1048575){$('status').className='status error';$('status').textContent='O detalhamento excede o limite de linhas do Excel.';return;}const detail=['Número da linha','Regra não atendida','Classificação','Valor encontrado','Valor esperado','Município','UF','Data de referência'],summary=['Regra não atendida','Quantidade de ocorrências','Classificação'],rules=['Número da regra','Colunas','Regra','Classificação'],details=reportRows.map(row=>[row[0],row[1],classificationLabel(row[2]),...row.slice(3)]),appliedRules=REGRAS.map(row=>[...row.slice(0,2),displayRuleText(row[2]),classificationLabel(row[3])]),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet([summary,...summaryRows()],2),'LOG RESUMO');XLSX.utils.book_append_sheet(book,sheet([detail,...details],2),'LOG DETALHAMENTO');XLSX.utils.book_append_sheet(book,sheet([rules,...appliedRules],3),'REGRAS APLICADAS');XLSX.writeFile(book,`relatorio_reforma_casa_brasil_${new Date().toISOString().slice(0,10)}.xlsx`,{cellStyles:true});});
$('copiar-incidente').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('texto-incidente').value);}catch(_){$('texto-incidente').select();document.execCommand('copy');}$('status-copia').className='status ok';$('status-copia').textContent='Texto copiado. Você pode ajustá-lo antes ou depois de colar no e-mail.';});
